version: 0.1
phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      # clear S3 bucket
      - aws s3 rm s3://my-react-study --recursive

      # copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./build s3://my-react-study/

      # set the cache-control headers for service-worker.js to prevent
      # browser caching
      #- >
      #  aws s3 cp --acl public-read 
      #  --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
      #  ./build/service-worker.js s3://welcome-board-app/

      # set the cache-control headers for index.html to prevent
      # browser caching
      - >
        aws s3 cp --acl public-read 
        --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
        ./build/index.html s3://my-react-study/
artifacts:
  files:
    - "**/*"
  base-directory: build